channels:
- conda-forge
dependencies:
- python=3.12.9
- pip<=24.3.1
- pip:
  - mlflow==2.20.2
  - cloudpickle==3.1.1
  - matplotlib==3.10.0
  - numpy==2.1.0
  - pandas==2.2.3
  - psutil==6.1.1
  - scikit-learn==1.6.1
  - scipy==1.15.1
name: mlflow-env
